[build]
providers = ["python"]

[phases.setup]
aptPkgs = ["libcairo2-dev", "libgirepository1.0-dev", "gcc", "libcairo2", "libcairo-gobject2", "pkg-config"]

[variables]
LD_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu:/usr/lib:/lib/x86_64-linux-gnu:/lib:/usr/local/lib"
PKG_CONFIG_PATH = "/usr/lib/x86_64-linux-gnu/pkgconfig"

[start]
cmd = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn qr_project.wsgi --bind 0.0.0.0:$PORT"
