[build]
providers = ["python"]

[phases.setup]
aptPkgs = ["libcairo2-dev", "libgirepository1.0-dev", "gcc"]

[phases.install]
cmds = ["/opt/venv/bin/pip install -r requirements.txt"]

[start]
cmd = "/opt/venv/bin/python manage.py migrate && /opt/venv/bin/python manage.py collectstatic --noinput && /opt/venv/bin/gunicorn qr_project.wsgi --bind 0.0.0.0:$PORT"
