[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[deploy.environmentVariables]]
name = "DJANGO_SETTINGS_MODULE"
value = "qr_project.settings"

[[deploy.environmentVariables]]
name = "DEBUG"
value = "False"
