# Generated by Django 5.2.4 on 2025-08-13 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRBatchDjango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='logos/')),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2')], max_length=10)),
                ('block_width_mm', models.FloatField()),
                ('block_height_mm', models.FloatField()),
                ('spacing_mm', models.FloatField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
            options={
                'db_table': 'qrgen_qrbatch',
            },
        ),
        migrations.CreateModel(
            name='QRCodeDjango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.FileField(upload_to='qr_codes/')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrgen.qrbatchdjango')),
            ],
            options={
                'db_table': 'qrgen_qrcode',
            },
        ),
    ]
